DROP TABLE IF EXISTS routes;

CREATE TABLE routes (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  location TEXT NOT NULL,
  name TEXT NOT NULL,
  rating TEXT NOT NULL,
  notes TEXT NOT NULL
)
